import { Router, type IRouter } from "express";
import healthRouter from "./health";
import todayRouter from "./today";
import propertiesRouter from "./properties";
import pipelineRouter from "./pipeline";
import jobsRouter from "./jobs";
import jobBoardRouter from "./jobboard";
import moneyRouter from "./money";
import inventoryRouter from "./inventory";
import activityRouter from "./activity";
import voiceRouter from "./voice";
import ingestRouter from "./ingest";
import notifyRouter from "./notify";
import storageRouter from "./storage";
import crewRouter from "./crew";
import portalRouter from "./portal";
import packetsRouter from "./packets";
import calendarRouter from "./calendar";
import settingsRouter from "./settings";
import plaidRouter from "./plaid";
import geoRouter from "./geo";
import arrivalsRouter from "./arrivals";
import accountingRouter from "./accounting";
import taxPlannerRouter from "./taxPlanner";
import vapiRouter from "./vapi";
import wingsRouter from "./wings";
import payhubRouter from "./payhub";
import sopRouter from "./sop";
import adminRouter from "./admin";
import jobSummariesRouter from "./jobSummaries";
import clientAccessRouter from "./clientAccess";
import workRequestsRouter from "./workRequests";
import invoiceJobDraftRouter from "./invoiceJobDraft";
import clientBoardRouter from "./clientBoard";

const router: IRouter = Router();

router.use(healthRouter);
router.use(todayRouter);
router.use(propertiesRouter);
router.use(pipelineRouter);
router.use(jobsRouter);
router.use(jobBoardRouter);
router.use(moneyRouter);
router.use(inventoryRouter);
router.use(activityRouter);
router.use(voiceRouter);
router.use(ingestRouter);
router.use(notifyRouter);
router.use(storageRouter);
router.use(crewRouter);
router.use(portalRouter);
router.use(packetsRouter);
router.use(calendarRouter);
router.use(settingsRouter);
router.use(plaidRouter);
router.use(geoRouter);
router.use(arrivalsRouter);
router.use(accountingRouter);
router.use(taxPlannerRouter);
router.use(vapiRouter);
router.use(wingsRouter);
router.use(payhubRouter);
router.use(sopRouter);
router.use(adminRouter);
router.use(jobSummariesRouter);
router.use(clientAccessRouter);
router.use(clientBoardRouter);
router.use(workRequestsRouter);
router.use(invoiceJobDraftRouter);

export default router;
