import { Router, type IRouter } from "express";
import healthRouter from "./health";
import todayRouter from "./today";
import propertiesRouter from "./properties";
import pipelineRouter from "./pipeline";
import jobsRouter from "./jobs";
import jobBoardRouter from "./jobboard";
import moneyRouter from "./money";
import inventoryRouter from "./inventory";
import activityRouter from "./activity";
import voiceRouter from "./voice";
import ingestRouter from "./ingest";
import notifyRouter from "./notify";
import storageRouter from "./storage";
import crewRouter from "./crew";
import portalRouter from "./portal";
import packetsRouter from "./packets";
import calendarRouter from "./calendar";
import settingsRouter from "./settings";
import plaidRouter from "./plaid";
import geoRouter from "./geo";
import accountingRouter from "./accounting";
import taxPlannerRouter from "./taxPlanner";

const router: IRouter = Router();

router.use(healthRouter);
router.use(todayRouter);
router.use(propertiesRouter);
router.use(pipelineRouter);
router.use(jobsRouter);
router.use(jobBoardRouter);
router.use(moneyRouter);
router.use(inventoryRouter);
router.use(activityRouter);
router.use(voiceRouter);
router.use(ingestRouter);
router.use(notifyRouter);
router.use(storageRouter);
router.use(crewRouter);
router.use(portalRouter);
router.use(packetsRouter);
router.use(calendarRouter);
router.use(settingsRouter);
router.use(plaidRouter);
router.use(geoRouter);
router.use(accountingRouter);
router.use(taxPlannerRouter);

export default router;
