import { pgTable, uuid, text, timestamp, jsonb, integer } from "drizzle-orm/pg-core";
export const workReviewsTable = pgTable("work_reviews", {
  id: uuid("id").primaryKey().defaultRandom(),
  jobId: uuid("job_id").notNull(),
  status: text("status").notNull().default("pending_field"),
  trigger: text("trigger").notNull().default("dispatch_scan"),
  verificationSnapshot: jsonb("verification_snapshot"),
  fieldEdits: jsonb("field_edits"),
  fieldSubmittedAt: timestamp("field_submitted_at", { withTimezone: true }),
  fieldSubmittedBy: text("field_submitted_by"),
  botFinalSnapshot: jsonb("bot_final_snapshot"),
  marginReport: jsonb("margin_report"),
  botDecision: text("bot_decision"),
  botNotes: text("bot_notes"),
  discrepancyCount: integer("discrepancy_count").default(0),
  invoiceQueuedAt: timestamp("invoice_queued_at", { withTimezone: true }),
  fieldNotifiedAt: timestamp("field_notified_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export const workReportCardsTable = pgTable("work_report_cards", {
  id: uuid("id").primaryKey().defaultRandom(),
  reviewId: uuid("review_id"),
  jobId: uuid("job_id").notNull(),
  jobNo: text("job_no"),
  unitNo: text("unit_no"),
  stage: text("stage").notNull(),
  title: text("title").notNull(),
  summary: text("summary"),
  card: jsonb("card").notNull(),
  marginReport: jsonb("margin_report"),
  actor: text("actor"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
